package pfecoop;

import Controler.Traitement;
import database.Database;
import database.ResultSetTableModel;
import database.test_bdd;
import database.test_parameter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class Adherents extends javax.swing.JFrame {

    test_bdd db;
        DefaultTableModel dm;
        Database bdd;
        //test_bdd db;
        Connection con;
        ResultSet rs;
        PreparedStatement ps;
    public Adherents() {
        db = new test_bdd(new test_parameter().HOST_DB, new test_parameter().USERNAME_DB, new test_parameter().PASSWORD_DB, new test_parameter().IPHOST, new test_parameter().PORT);
        initComponents();
        this.setSize(1400, 800);
        this.setLocationRelativeTo(this);
        
    }
     public void table() {
        String liste[] = {"id,code,civilite,nom,prenom,cin,tranche_age,date_naissance,lieu_naissance,"
                + "situation_familiale,nombre_enfants,nom_pere,nom_mere,adresse_village,adresse_commune,niveau_etude,"
                + "nombre_parcelles,lieu_parcelles,qte_safran_deposee,pertes,prix_achat,date_depot,date_prod,excedent,"
                + "nombre_parts_sociales,montant_parts_sociales"};

    }
    private void filtre(String query)
    {
        TableRowSorter<DefaultTableModel>tr=new TableRowSorter<DefaultTableModel>(dm);
        tab_a.setRowSorter(tr);
        if(query!="None")
        {
            tr.setRowFilter(RowFilter.regexFilter(query));
        }
        else
        {
            tab_a.setRowSorter(tr);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_a = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(218, 182, 238));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 530));
        jPanel1.setLayout(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(270, 10, 270, 50);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfecoop/Rechercher.jpg"))); // NOI18N
        jButton1.setText(" Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(70, 10, 181, 50);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfecoop/Modifier.png"))); // NOI18N
        jButton2.setText("   Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(870, 10, 190, 50);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfecoop/Supprimer.png"))); // NOI18N
        jButton4.setText("  Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1090, 10, 183, 50);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tab_a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tab_a.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Code", "Civilité", "Nom", "Prénom", "CIN", "Tranche d'âge", "Date de naissance", "Lieu de naissance", "Situation familiale", "Nbre d'enfants", "Nom du père", "Nom de la mère", "Adresse (Village)", "Adresse (Commune rurale)", "Niveau d'études", "Nbre de parcelles", "Lieu des parcelles", "Qté déposée", "Pertes", "Prix d'achat", "Date de dépôt", "Date de production", "Excédent", "Nombre des parts sociales", "Montant des parts sociales"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tab_a.setGridColor(new java.awt.Color(102, 102, 102));
        tab_a.setSelectionBackground(new java.awt.Color(255, 204, 204));
        tab_a.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tab_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_aMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tab_a);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 70, 1340, 90);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Logs\\Stage Zineb\\Retour.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1300, 10, 50, 50);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Code", "Civilité", "Nom", "Prénom", "CIN", "Tranche d'âge", "Date de naissance", "Lieu de naissance", "Situation familiale", "Nbre d'enfants", "Nom du père", "Nom de la mère", "Adresse (Village)", "Adresse (Commune rurale)", "Niveau d'études", "Nbre de parcelles", "Lieu des parcelles", "Quantité de safran déposée", "Pertes", "Prix d'achat", "Date de dépôt", "Date de production", "Excédent", "Nbre des parts sociales", "Montant des parts sociales" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(560, 10, 210, 50);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("ID");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(30, 180, 200, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(320, 590, 230, 30);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M.", "Mme" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(320, 240, 230, 30);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< 16 ans", "16 - 24 ans", "25 - 34 ans", "35 - 49 ans", "50 - 64 ans", "> 65 ans" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(320, 380, 230, 30);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Célibataire", "Marié(e)", "Divorcé(e)", "Veuf(ve)" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(320, 480, 230, 30);

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agadir Melloul", "Askaoun", "Assaki", "Assays", "Sidi Hssaine", "Taliouine", "Tassousfi", "Zagmouzen" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(1080, 200, 230, 30);

        jComboBox6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licence", "DEUG", "BAC", "4ème", "Primaire", "Aucun" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox6);
        jComboBox6.setBounds(1080, 240, 230, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfecoop/Actualiser.png"))); // NOI18N
        jButton5.setText(" Actualiser");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(880, 640, 180, 50);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfecoop/Effacer.png"))); // NOI18N
        jButton6.setText("  Effacer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(340, 640, 170, 50);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Code");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(30, 210, 210, 22);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Civilité");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(30, 242, 200, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Nom");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(30, 280, 120, 22);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Prénom");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(30, 310, 210, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("CIN");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(30, 350, 190, 22);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Tranche d'âge");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(30, 380, 210, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Date de naissance");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(30, 410, 180, 30);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setText("Lieu de naissance");
        jPanel1.add(jLabel39);
        jLabel39.setBounds(30, 450, 160, 22);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Situation familiale");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(30, 482, 163, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("Nombre d'enfants");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(30, 520, 162, 22);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Nom du père");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(30, 550, 230, 30);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setText("Nom de la mère");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(30, 590, 230, 22);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("Adresse (Village)");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(710, 180, 290, 22);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setText("Adresse (Commune rurale)");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(710, 210, 300, 22);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("Niveau d'études");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(710, 240, 270, 22);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setText("Nombre de parcelles");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(710, 270, 270, 22);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setText("Lieu des parcelles");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(710, 300, 270, 30);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setText("Quantité de safran déposée (g)");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(710, 330, 281, 40);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setText("Pertes (g)");
        jPanel1.add(jLabel38);
        jLabel38.setBounds(710, 370, 290, 30);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setText("Prix d'achat (DH)");
        jPanel1.add(jLabel40);
        jLabel40.setBounds(710, 410, 290, 22);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel41.setText("Date de dépôt");
        jPanel1.add(jLabel41);
        jLabel41.setBounds(710, 448, 270, 30);

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel42.setText("Date de production");
        jPanel1.add(jLabel42);
        jLabel42.setBounds(710, 480, 290, 40);

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel43.setText("Excédent (DH)");
        jPanel1.add(jLabel43);
        jLabel43.setBounds(710, 522, 280, 30);

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel44.setText("Nombre des parts sociales");
        jPanel1.add(jLabel44);
        jLabel44.setBounds(710, 560, 280, 22);

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel45.setText("Montant des parts sociales (DH)");
        jPanel1.add(jLabel45);
        jLabel45.setBounds(710, 590, 288, 30);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(320, 210, 230, 30);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(320, 270, 230, 30);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(320, 310, 230, 30);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(320, 350, 230, 30);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9);
        jTextField9.setBounds(320, 410, 230, 30);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(320, 450, 230, 30);
        jPanel1.add(jTextField11);
        jTextField11.setBounds(320, 510, 230, 30);
        jPanel1.add(jTextField12);
        jTextField12.setBounds(320, 550, 230, 30);
        jPanel1.add(jTextField13);
        jTextField13.setBounds(320, 170, 230, 30);

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField14);
        jTextField14.setBounds(1080, 170, 230, 30);
        jPanel1.add(jTextField15);
        jTextField15.setBounds(1080, 270, 230, 30);
        jPanel1.add(jTextField16);
        jTextField16.setBounds(1080, 300, 230, 30);
        jPanel1.add(jTextField17);
        jTextField17.setBounds(1080, 340, 230, 30);
        jPanel1.add(jTextField18);
        jTextField18.setBounds(1080, 370, 230, 30);
        jPanel1.add(jTextField19);
        jTextField19.setBounds(1080, 410, 230, 30);
        jPanel1.add(jTextField20);
        jTextField20.setBounds(1080, 590, 230, 30);
        jPanel1.add(jTextField21);
        jTextField21.setBounds(1080, 450, 230, 30);
        jPanel1.add(jTextField22);
        jTextField22.setBounds(1080, 480, 230, 30);
        jPanel1.add(jTextField23);
        jTextField23.setBounds(1080, 520, 230, 30);
        jPanel1.add(jTextField24);
        jTextField24.setBounds(1080, 560, 230, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Logs\\Stage Zineb\\Logo.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 48, 48);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfecoop/Ajouter.png"))); // NOI18N
        jButton8.setText("  Ajouter");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(610, 640, 180, 50);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(780, 30, 70, 0);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1400, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       //
        int index = tab_a.getSelectedRow();
        String id = tab_a.getValueAt(index, 0).toString();
        if (new Traitement().Modifier(id,jTextField5.getText(), jComboBox2.getSelectedItem().toString(), jTextField6.getText(), jTextField7.getText(), jTextField8.getText(), jComboBox3.getSelectedItem().toString(), jTextField9.getText(), jTextField10.getText(), jComboBox4.getSelectedItem().toString(), jTextField11.getText(), jTextField12.getText(), jTextField3.getText(), jTextField14.getText(), jComboBox5.getSelectedItem().toString(), jComboBox6.getSelectedItem().toString(), jTextField15.getText(), jTextField16.getText(), jTextField17.getText(),jTextField18.getText(),jTextField19.getText(),jTextField21.getText(),jTextField22.getText(),jTextField23.getText(),jTextField24.getText(),jTextField20.getText())) {
            JOptionPane.showMessageDialog(null, "La modification a bien été effectuée !");
            jTextField5.setText("");
            jComboBox2.setSelectedItem("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jComboBox3.setSelectedItem("");
            jTextField9.setText("");
            jTextField10.setText("");
            jComboBox4.setSelectedItem("");
            jTextField11.setText("");
            jTextField12.setText("");
            jTextField3.setText("");
            jTextField14.setText("");
            jComboBox5.setSelectedItem("");
            jComboBox6.setSelectedItem("");
            jTextField15.setText("");
            jTextField16.setText("");
            jTextField17.setText("");
            jTextField18.setText("");
            jTextField19.setText("");
            jTextField21.setText("");
            jTextField22.setText("");
            jTextField23.setText("");
            jTextField24.setText("");
            jTextField20.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "La modification n'a pas été effectuée !");
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Suppression
        String[] option = {"Oui", "Non"};
        int rep = JOptionPane.showOptionDialog(null, "Êtes-vous sûr de vouloir supprimer ?", "Suppression confirmée !", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, option, option[1]);
        if (rep == 0) {
            int index = tab_a.getSelectedRow();
            String id = tab_a.getValueAt(index, 0).toString();
            if (new Traitement().Supprimer(id)) {
                JOptionPane.showMessageDialog(null, "Suppression confirmée !");
                jTextField5.setText("");
                jComboBox2.setSelectedItem("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");
                jComboBox3.setSelectedItem("");
                jTextField9.setText("");
                jTextField10.setText("");
                jComboBox4.setSelectedItem("");
                jTextField11.setText("");
                jTextField12.setText("");
                jTextField3.setText("");
                jTextField14.setText("");
                jComboBox5.setSelectedItem("");
                jComboBox6.setSelectedItem("");
                jTextField15.setText("");
                jTextField16.setText("");
                jTextField17.setText("");
                jTextField18.setText("");
                jTextField19.setText("");
                jTextField21.setText("");
                jTextField22.setText("");
                jTextField23.setText("");
                jTextField24.setText("");
                jTextField20.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Suppression annulée !");
            }

        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tab_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_aMouseClicked
        // TODO add your handling code here:
        String code = tab_a.getValueAt(tab_a.getSelectedRow(), 1).toString();
        String civilite = tab_a.getValueAt(tab_a.getSelectedRow(), 2).toString();
        String nom = tab_a.getValueAt(tab_a.getSelectedRow(), 3).toString();
        String prenom = tab_a.getValueAt(tab_a.getSelectedRow(), 4).toString();
        String cin = tab_a.getValueAt(tab_a.getSelectedRow(), 5).toString();
        String tranche_age = tab_a.getValueAt(tab_a.getSelectedRow(), 6).toString();
        String date_naissance = tab_a.getValueAt(tab_a.getSelectedRow(), 7).toString();
        String lieu_naissance = tab_a.getValueAt(tab_a.getSelectedRow(), 8).toString();
        String situation_familiale = tab_a.getValueAt(tab_a.getSelectedRow(), 9).toString();
        String nombre_enfants = tab_a.getValueAt(tab_a.getSelectedRow(), 10).toString();
        String nom_pere = tab_a.getValueAt(tab_a.getSelectedRow(), 11).toString();
        String nom_mere = tab_a.getValueAt(tab_a.getSelectedRow(), 12).toString();
        String adresse_village = tab_a.getValueAt(tab_a.getSelectedRow(), 13).toString();
        String adresse_commune = tab_a.getValueAt(tab_a.getSelectedRow(), 14).toString();
        String niveau_etude = tab_a.getValueAt(tab_a.getSelectedRow(), 15).toString();
        String nombre_parcelles = tab_a.getValueAt(tab_a.getSelectedRow(), 16).toString();
        String lieu_parcelles = tab_a.getValueAt(tab_a.getSelectedRow(), 17).toString();
        String qte_safran_deposee = tab_a.getValueAt(tab_a.getSelectedRow(), 18).toString();
        String pertes = tab_a.getValueAt(tab_a.getSelectedRow(), 19).toString();
        String prix_achat = tab_a.getValueAt(tab_a.getSelectedRow(), 20).toString();
        String date_depot = tab_a.getValueAt(tab_a.getSelectedRow(), 21).toString();
        String date_prod = tab_a.getValueAt(tab_a.getSelectedRow(), 22).toString();
        String excedent = tab_a.getValueAt(tab_a.getSelectedRow(), 23).toString();
        String nombre_parts_sociales = tab_a.getValueAt(tab_a.getSelectedRow(), 24).toString();
        String montant_parts_sociales = tab_a.getValueAt(tab_a.getSelectedRow(), 25).toString();

        jTextField5.setText(code);
        jComboBox2.setSelectedItem(civilite);
        jTextField6.setText(nom);
        jTextField7.setText(prenom);
        jTextField8.setText(cin);
        jComboBox3.setSelectedItem(tranche_age);
        jTextField9.setText(date_naissance);
        jTextField10.setText(lieu_naissance);
        jComboBox4.setSelectedItem(situation_familiale);
        jTextField11.setText(nombre_enfants);
        jTextField12.setText(nom_pere);
        jTextField3.setText(nom_mere);
        jTextField14.setText(adresse_village);
        jComboBox5.setSelectedItem(adresse_commune);
        jComboBox6.setSelectedItem(niveau_etude);
        jTextField15.setText(nombre_parcelles);
        jTextField16.setText(lieu_parcelles);
        jTextField17.setText(qte_safran_deposee);
        jTextField18.setText(pertes);
        jTextField19.setText(prix_achat);
        jTextField21.setText(date_depot);
        jTextField22.setText(date_prod);
        jTextField23.setText(excedent);
        jTextField24.setText(nombre_parts_sociales);
        jTextField20.setText(montant_parts_sociales);
    }//GEN-LAST:event_tab_aMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Accueil clA = new Accueil();
        clA.setVisible(true);
        this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     DefaultTableModel dm = new Traitement().getdata();
        tab_a.setModel(dm);   // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //Effacer
        jTextField13.setText("");
        jTextField5.setText("");
        jComboBox2.setSelectedItem("M.");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jComboBox3.setSelectedItem("< 16 ans");
        jTextField9.setText("");
        jTextField10.setText("");
        jComboBox4.setSelectedItem("Célibataire");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField3.setText("");
        jTextField14.setText("");
        jComboBox5.setSelectedItem("Agadir Melloul");
        jComboBox6.setSelectedItem("Licence");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField18.setText("");
        jTextField19.setText("");
        jTextField21.setText("");
        jTextField22.setText("");
        jTextField23.setText("");
        jTextField24.setText("");
        jTextField20.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //Ajout
// TODO add your handling code here:
        if (new Traitement().Ajouter(jTextField5.getText(), jComboBox2.getSelectedItem().toString(), jTextField6.getText(), jTextField7.getText(), jTextField8.getText(), jComboBox3.getSelectedItem().toString(), jTextField9.getText(), jTextField10.getText(), jComboBox4.getSelectedItem().toString(), jTextField11.getText(), jTextField12.getText(), jTextField3.getText(), jTextField14.getText(), jComboBox5.getSelectedItem().toString(), jComboBox6.getSelectedItem().toString(), jTextField15.getText(), jTextField16.getText(), jTextField17.getText(),jTextField18.getText(),jTextField19.getText(),jTextField21.getText(),jTextField22.getText(),jTextField23.getText(),jTextField24.getText(),jTextField20.getText()) )
        {
        JOptionPane.showMessageDialog(null, "L'adhérent a bien été ajouté !");
       
        jTextField5.setText("");
        jComboBox2.setSelectedItem("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jComboBox3.setSelectedItem("");
        jTextField9.setText("");
        jTextField10.setText("");
        jComboBox4.setSelectedItem("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField3.setText("");
        jTextField14.setText("");
        jComboBox5.setSelectedItem("");
        jComboBox6.setSelectedItem("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField18.setText("");
        jTextField19.setText("");
        jTextField21.setText("");
        jTextField22.setText("");
        jTextField23.setText("");
        jTextField24.setText("");
        jTextField20.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "L'adhérent n'a pas été ajouté !");
        }                                          
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         //Recherche
        if (jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Veuillez entrer quelque chose !");
        } else {
          
            if (jComboBox1.getSelectedItem().equals("ID")) {
                rs = db.querySelectAll("adherent", "id LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Code")) {
                rs = db.querySelectAll("adherent", "code LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Civilité")) {
                rs = db.querySelectAll("adherent", "civilite LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Nom")) {
                rs = db.querySelectAll("adherent", "nom LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Prénom")) {
                rs = db.querySelectAll("adherent", "prenom LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("CIN")) {
                rs = db.querySelectAll("adherent", "cin LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Tranche d'âge")) {
                rs = db.querySelectAll("adherent", "tranche_age LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Date de naissance")) {
                rs = db.querySelectAll("adherent", "date_naissance LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Lieu de naissance")) {
                rs = db.querySelectAll("adherent", "lieu_naissance LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Situation familiale")) {
                rs = db.querySelectAll("adherent", "situation_familiale LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Nombre d'enfants")) {
                rs = db.querySelectAll("adherent", "nombre_enfants LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Nom du père")) {
                rs = db.querySelectAll("adherent", "nom_pere LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Nom de la mère")) {
                rs = db.querySelectAll("adherent", "nom_mere LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Adresse (Village)")) {
                rs = db.querySelectAll("adherent", "adresse_village LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Adresse (Commune rurale)")) {
                rs = db.querySelectAll("adherent", "adresse_commune LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Niveau d'études")) {
                rs = db.querySelectAll("adherent", "niveau_etude LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Nombre de parcelles")) {
                rs = db.querySelectAll("adherent", "nombre_parcelles LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Lieu des parcelles")) {
                rs = db.querySelectAll("adherent", "lieu_parcelles LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Quantité de safran déposée (g)")) {
                rs = db.querySelectAll("adherent", "qte_safran_deposee LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Pertes (g)")) {
                rs = db.querySelectAll("adherent", "pertes LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Prix d'achat (DH)")) {
                rs = db.querySelectAll("adherent", "prix_achat LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Date de dépôt")) {
                rs = db.querySelectAll("adherent", "date_depot LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Date de production")) {
                rs = db.querySelectAll("adherent", "date_prod LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Excédent (DH)")) {
                rs = db.querySelectAll("adherent", "excedent LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Nombre des parts sociales")) {
                rs = db.querySelectAll("adherent", "nombre_parts_sociales LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            } else if (jComboBox1.getSelectedItem().equals("Montant des parts sociales (DH)")) {
                rs = db.querySelectAll("adherent", "montant_parts_sociales LIKE '%" + jTextField1.getText() + "%' ");
                tab_a.setModel(new ResultSetTableModel(rs));
            }
        }   // TODO add your handling code here:
       
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        /*Calendar cal = new GregorianCalendar();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            dateFormat.setTimeZone(cal.getTimeZone());
            jLabel2.setText(dateFormat.format(cal.getTime())); */  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adherents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adherents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adherents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adherents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adherents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable tab_a;
    // End of variables declaration//GEN-END:variables
}
